### ISSUE TITLE
Time Playing does not update

### ISSUE THREAD

**Issue by ScrappyCocco** [SlashNephy/Hypixthon#1]
The "Time Playing" value it's always the same for me, i mean:
If 1 month ago was 400 now is still 400 (and i played on hypixel)
What could be?

**Comment by SlashNephy** [comment]
Hi ScrappyCocco.

Thank you for visiting my repo. This library uses Hypixel Official API (https://api.hypixel.net/).
But it does NOT cache api responses. So the "Time Playing" value depends on Hypixel API.

Please contact with Hypixel developers.

Regards,
Slash Nephy
